<?php
// This file is generated by scripts/gen-autoload.php, do not adjust manually
// @codingStandardsIgnoreFile
global $wgAutoloadClasses;

$wgAutoloadClasses += array(
    'SpecialGiveMeThumbUp' => __DIR__ . '/Specials/SpecialGiveMeThumbUp.php',
    'SystemMessageClass' => __DIR__ . '/SystemMessageClass.php'
);
